
# docker compose up [ --build --detach ]

# https://docs.docker.com/compose/compose-file/compose-versioning/
version: '3.8'

services:
  django:
    image: django-docker:0.0.1
    # image: docker-registry.qualcomm.com/repository/obrien/django-docker:0.0.1
    # image: docker-registry.qualcomm.com/organization/isrm/django-docker:0.0.1    
    build: .
    # the following override image defaults and those set by build ./Dockerfile processing
    ports: 
      - "8000:8000"
    volumes:
      - .vscode/.env.test:/app/.env
    env_file:
      - .vscode/.env.test
    # use following if you want to attach to container and debug starting django app yourself
    #command: tail -f /dev/null
    command: python3 manage.py runserver