
# docker compose up --build

version: '3.9'

services:
  django:
    image: docker-registry.qualcomm.com/repository/obrien/django-docker:0.0.1
    #image: docker-registry.qualcomm.com/organization/isrm/django-docker:0.0.1
    # build: .
    # ports: 
    #   - "8000:8000"
    # env_file:
    #   - .vscode/.env.dev
    # command: tail -f /dev/null