
# docker compose up --build --detach 
# https://bing.com/search?q=docker+compose+vs+docker-compose -> "The docker compose (with a space) is a newer project to migrate compose to Go with the rest of the docker project."

# https://docs.docker.com/compose/compose-file/compose-versioning/
version: '3.8'

services:
  django:
    image: django-docker:0.0.1
    # image: docker-registry.qualcomm.com/repository/obrien/django-docker:0.0.1
    # image: docker-registry.qualcomm.com/organization/isrm/django-docker:0.0.1    
    build: .
    # the following override image defaults and those set by build ./Dockerfile processing
    ports: 
      - 5678
      - 8000
    env_file: # doesn't appear to work and no --env-file command line switch alternative available 
      # - .vscode/.env.test
      # https://bing.com/search?q=docker-compose.yml+env_file+not+working
    volumes: # appears to get applied after /app/.env is applied to container environment settings
      - .vscode/.env.test:/app/.env
      # https://bing.com/search?q=docker-compose.yml+volumes+mapping+before+run
    # command: python3 manage.py runserver
    command: entrypoint.sh
    # command: tail -f /dev/null # if you want to attach to container and debug starting django app yourself
    